#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>
# Licensed under The GNU Public License Version 2 (or later)

import os
import subprocess
import tempfile

condor_job = '''
executable = /usr/local/bin/metropolis
arguments = --iter 10000 --corr-size 5 --time-step {time_step:f} --time-sites {time_sites:d} --iter-pre 2000 --iter-between 10 --irw 0 --inv-scatt-len 1 --gauss-width {gauss_width:f} --max-cores 1
log    = ID-$(Cluster).$(Process)-log.txt
output = ID-$(Cluster).$(Process)-out.txt
universe = vanilla
request_cpus = 1
queue
'''

def main():
    for sigma in [0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5]:
        for a in [0.005, 0.01, 0.05, 0.1, 0.2, 0.3]:
            tf = tempfile.TemporaryFile('w')
            N = max(int(150 / a), 1000)
            tf.write(condor_job.format(time_step=a, gauss_width=sigma, time_sites=N))
            tf.seek(0)

            subprocess.check_call('condor_submit', stdin=tf)
            print()

if __name__ == '__main__':
    main()
