#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

import argparse
import json
import os.path

import prettytable
import unitprint

def p(s):
    f = float(s)
    return unitprint.siunitx(f)

def main():
    options = _parse_args()

    table = prettytable.PrettyTable([
        'ID',
        'iter',
        'isl',
        'gauss_width',
        'corr_size',
        'time_sites',
        'time_step',
        'corr_max',
        'margin',
    ])

    for run in options.runs:
        filename = '{run}/{run}-options.js'.format(run=run)
        if not os.path.isfile(filename):
            continue

        with open(filename) as f:
            info = json.load(f)

        table.add_row([
            run,
            p(info['iterations']),
            p(info['inverse_scattering_length']),
            p(info['gauss_width']),
            p(info['correlation_size']),
            p(info['time_sites']),
            p(info['time_step']),
            p(info['correlation_ts'][-1] * info['time_step']),
            p(info['margin']),
        ])

    print(table)

def _parse_args():
    """
    Parses the command line arguments.

    If the logging module is imported, set the level according to the number of
    ``-v`` given on the command line.

    :return: Namespace with arguments.
    :rtype: Namespace
    """
    parser = argparse.ArgumentParser(description="")
    parser.add_argument("runs", nargs="+", help="Run IDs")

    options = parser.parse_args()

    return options

if __name__ == "__main__":
    main()
