#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

import argparse

import matplotlib.pyplot as pl
import mpl_toolkits.mplot3d.axes3d as p3
import numpy as np
import prettytable
import scipy.optimize as op
import unitprint

def make_col(data, col, ylabel, outfile):
    time_groups = {}
    for row in range(len(data[:, 1])):
        time_step = data[row, 1]
        if not time_step in time_groups:
            time_groups[time_step] = []
        time_groups[time_step].append((data[row, 0], data[row, col], data[row, col+1]))

    for time_step, items in sorted(time_groups.items()):
        items = np.array(items)
        items.sort(0)
        gauss_width = items[:, 0]
        y_val = items[:, 1]
        y_err = items[:, 2]

        pl.errorbar(gauss_width, y_val, yerr=y_err, label='a = {:f}'.format(time_step), marker='|')

    pl.xlabel(r'$G_\sigma$')
    pl.ylabel(ylabel)
    pl.grid(True)
    pl.margins(0.1)
    pl.legend(loc='best')
    #pl.show()
    pl.savefig(outfile)
    pl.clf()

def main():
    options = _parse_args()

    #pl.pcolormesh(raw_data[:, :-1])
    #pl.colorbar() 

    data = np.loadtxt(options.filename)

    make_col(data, 2, r'$E_0$', 'E0.pdf')
    make_col(data, 4, r'$E_2$', 'E2.pdf')
    make_col(data, 6, r'$E_2 - E_0$', 'E2-E0.pdf')
    make_col(data, 8, r'$E_4 - E_0$', 'E4-E0.pdf')
    make_col(data, 10, r'$E_4 - E_2$', 'E4-E2.pdf')


def _parse_args():
    """
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    """
    parser = argparse.ArgumentParser(description="")
    parser.add_argument('filename')

    options = parser.parse_args()

    return options

if __name__ == "__main__":
    main()
